sudo: required
services:
  - docker

before_install:
  - docker build -t xenus90/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true xenus90/react-test npm test

after_success:
  - docker build -t xenus90/multi-client ./client
  - docker build -t xenus90/multi-nginx ./nginx
  - docker build -t xenus90/multi-server ./server
  - docker build -t xenus90/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push xenus90/multi-client
  - docker push xenus90/multi-nginx
  - docker push xenus90/multi-server
  - docker push xenus90/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-057451935246
  bucket_path: docker_multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
